### ISSUE TITLE
Restore job killed in K8s

### ISSUE THREAD

**Issue by angonz** [hastexo/tutor-contrib-backup#54]
# Summary

Hi there,
I am testing the restore function in my K8s with a very large backup file (5.8G compressed, ~20G plain). It suddenly stops as the pod gets killed.

## What I did

`tutor k8s restore`

## What I expected to happen

With smaller files it works like a charm.

## My environment

* Tutor version: 14.0.5
* `tutor-contrib-backup` version: 1.2.0
* Output of the restore command: 

```
2022-10-20T15:04:21.429+0000    finished restoring edxmongo_mynamespace.users (8689 documents, 0 failures)
2022-10-20T15:04:21.561+0000    reading metadata for edxmongo_mynamespace.subscriptions from /data/mongodb_dump/edxmongo_mynamespace/subscriptions.metadata.json
2022-10-20T15:04:21.683+0000    [........................]   edxmongo_mynamespace.modulestore.structures  291MB/10.7GB   (2.7%)
2022-10-20T15:04:21.685+0000    [#.......................]                edxmongo_mynamespace.fs.chunks  343MB/6.60GB   (5.1%)
2022-10-20T15:04:21.685+0000    [#####...................]  edxmongo_mynamespace.modulestore.definitions   139MB/575MB  (24.1%)
2022-10-20T15:04:21.685+0000
2022-10-20T15:04:21.937+0000    restoring edxmongo_mynamespace.subscriptions from /data/mongodb_dump/edxmongo_mynamespace/subscriptions.bson
Killed
Traceback (most recent call last):
  File "restore_services.py", line 247, in <module>
    main()
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "restore_services.py", line 241, in main
    restore_mongodb()
  File "restore_services.py", line 77, in restore_mongodb
    check_call(cmd,
  File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mongorestore --stopOnError --drop --host=ip-10-0-9-66.ec2.internal --port=27017 /data/mongodb_dump --username=xxxx --password=xxxx' returned non-zero exit status 137.
```

Additionally, you might also want to add any of the items below, if you think they might be relevant to the bug:

* Kubernetes versions: 1.21

## Additional context

Looks like the pod is running out of memory while restoring MongoDB. I think we could add a memory request to the pod, but this should be an optional parameter. What do you think?

**Comment by fghaas** [comment]
If the issue is the pod being killed on account of excessive memory utilization, I would much prefer if we came up if we actually _used less_ memory on the restore, rather than than trying to request more. :)

I am not an expert on this, but I seem to recall that `mongorestore` memory utilization is related to the number of collections being restored in parallel. If I read [the 4.2 documentation](https://www.mongodb.com/docs/v4.2/reference/program/mongorestore/#cmdoption-mongorestore-numparallelcollections) correctly, the relevant command line option is `-j` and its default is 4. Do you think it may be prudent to reduce this to 1?

**Comment by angonz** [comment]
That would be great. The drawback is that it would increase the restore time. Maybe we can set it as an option, with 4 as a default.

Actually, I’ve tried to request more memory but then the pod never found a node with enough memory. So it’s much better to have the option to reduce the number of parallel restores.

Andrés


De: Florian Haas ***@***.***>
Fecha: lunes, 24 de octubre de 2022, 12:04
Para: hastexo/tutor-contrib-backup ***@***.***>
CC: Andres Gonzalez ***@***.***>, Author ***@***.***>
Asunto: Re: [hastexo/tutor-contrib-backup] Restore job killed in K8s (Issue #54)

If the issue is the pod being killed on account of excessive memory utilization, I would much prefer if we came up if we actually used less memory on the restore, rather than than trying to request more. :)

I am not an expert on this, but I seem to recall that mongorestore memory utilization is related to the number of collections being restored in parallel. If I read the 4.2 documentation<https://www.mongodb.com/docs/v4.2/reference/program/mongorestore/#cmdoption-mongorestore-numparallelcollections> correctly, the relevant command line option is -j and its default is 4. Do you think it may be prudent to reduce this to 1?

**Comment by fghaas** [comment]
I think the best way to do this would be to add a config value named `MONGORESTORE_ADDITIONAL_OPTIONS` and add those options to `cmd` here, if set:

https://github.com/hastexo/tutor-contrib-backup/blob/a44a0d6bb0f72970da97ebcb7aed70e44660a560/tutorbackup/templates/backup/build/backup/restore_services.py#L66-L75

Then, you could set `BACKUP_MONGORESTORE_ADDITIONAL_OPTIONS` to `"-j 1"`, and your restore process would be less memory hungry. If unset, it would simply use whatever the default for `-j` is for the `mongorestore` version that's being used.

Would you like to submit a PR for that?

**Comment by angonz** [comment]
Worked!!! I've tested in my K8s with the large backup with and without the option, and also in local.
Created [PR #55 ](https://github.com/hastexo/tutor-contrib-backup/pull/55)
